export const healthStyles = {
  screen: {
    minHeight:    '100dvh',
    background:   'var(--color-bg)',
    color:        'var(--color-text)',
    paddingBottom: 'calc(var(--safe-bottom) + var(--nav-height) + 18px)',
  },
  top: {
    position:   'sticky',
    top:        0,
    zIndex:     20,
    padding:    'max(env(safe-area-inset-top), 18px) 20px 8px',
    background: 'color-mix(in srgb, var(--color-bg) 98%, transparent)',
  },
  topHeader: {
    marginBottom: '7px',
  },
  topEyebrow: {
    margin:        0,
    color:         'var(--color-muted)',
    fontSize:      '10px',
    fontWeight:    700,
    letterSpacing: '0.1em',
  },
  tabs: {
    display:    'flex',
    alignItems: 'center',
    gap:        '6px',
    padding:    0,
    background: 'transparent',
  },
  tab: {
    minHeight:    '26px',
    border:       'var(--border)',
    borderRadius: '999px',
    background:   'transparent',
    color:        'var(--color-muted)',
    fontSize:     '11px',
    fontWeight:   650,
    padding:      '4px 10px',
  },
  tabActive: {
    borderColor: 'color-mix(in srgb, var(--color-accent) 44%, var(--color-border))',
    background:  'color-mix(in srgb, var(--color-accent-bg) 42%, transparent)',
    color:       'var(--color-text)',
  },
  today: {
    padding:       '4px 20px 0',
    display:       'flex',
    flexDirection: 'column',
    gap:           '6px',
  },
  simpleScreen: {
    minHeight:     '100dvh',
    padding:       '6px 20px 0',
  },
  trainingScreen: {
    minHeight:     '100dvh',
    padding:       '6px 0 0',
  },
  trainingHeader: {
    margin:  '0 20px 2px',
  },
  header: {
    display:       'flex',
    flexDirection: 'column',
    gap:           '1px',
    margin:        '0 0 1px',
  },
  eyebrow: {
    margin:        0,
    color:         'var(--color-muted)',
    fontSize:      '10px',
    fontWeight:    650,
    letterSpacing: '0',
    textTransform: 'lowercase',
  },
  title: {
    margin:      0,
    fontFamily: 'var(--font-display)',
    fontSize:   '16px',
    fontWeight: 500,
    lineHeight: 1.08,
  },
  subtitle: {
    margin:    '2px 0 0',
    color:     'var(--color-muted)',
    fontSize:  '11px',
    lineHeight: 1.3,
  },
  block: {
    display:       'flex',
    flexDirection: 'column',
    gap:           '4px',
    padding:       '8px 0 10px',
    borderTop:     '0.5px solid color-mix(in srgb, var(--color-border) 54%, transparent)',
    background:    'transparent',
  },
  plannerCard: {
    display:       'flex',
    flexDirection: 'column',
    padding:       '6px 0 0',
    background:    'transparent',
  },
  plannerTitle: {
    margin:        '0 0 4px',
    color:         'var(--color-muted)',
    fontSize:      '10px',
    fontWeight:    680,
    letterSpacing: '0.02em',
  },
  plannerGroup: {
    display:       'flex',
    flexDirection: 'column',
    gap:           '1px',
    padding:       '8px 0 7px',
    borderTop:     '0.5px solid color-mix(in srgb, var(--color-border) 44%, transparent)',
  },
  groupLabel: {
    margin:     '0 0 2px',
    color:      'var(--color-muted)',
    fontSize:   '11px',
    fontWeight: 640,
  },
  groupRows: {
    display:       'flex',
    flexDirection: 'column',
    gap:           '1px',
  },
  trainingBlock: {
    margin:  '0 20px 2px',
  },
  trainingPlanner: {
    paddingTop: '4px',
  },
  emptyCopy: {
    margin:    '2px 0 0',
    color:     'var(--color-muted)',
    fontSize:  '11px',
    lineHeight: 1.32,
  },
  typeList: {
    display:       'flex',
    flexDirection: 'column',
    gap:           '2px',
    marginTop:     '8px',
    paddingTop:    '10px',
    borderTop:     'var(--border)',
  },
  sectionHeader: {
    display:       'flex',
    flexDirection: 'column',
    gap:           0,
    marginBottom:  0,
  },
  sectionTitle: {
    margin:      0,
    fontFamily: 'var(--font-body)',
    fontSize:   '12px',
    fontWeight: 650,
    lineHeight: 1.1,
    textTransform: 'none',
  },
  sectionLabel: {
    margin:        0,
    color:         'var(--color-muted)',
    fontSize:      '10px',
    fontWeight:    700,
    letterSpacing: '0.1em',
  },
  trainingWeekList: {
    display:           'flex',
    gap:               '5px',
    marginTop:         0,
    paddingBottom:     '8px',
    overflowX:         'auto',
    scrollbarWidth:    'none',
    msOverflowStyle:   'none',
    WebkitOverflowScrolling: 'touch',
    borderBottom:      '0.5px solid color-mix(in srgb, var(--color-border) 44%, transparent)',
  },
  trainingWeekDay: {
    display:       'flex',
    flexDirection: 'column',
    alignItems:     'center',
    justifyContent: 'center',
    gap:            '3px',
    minWidth:       '54px',
    minHeight:      '42px',
    padding:        '6px 7px',
    border:         'var(--border)',
    borderRadius:   'var(--radius-sm)',
    background:     'transparent',
    color:          'var(--color-muted)',
  },
  trainingWeekDaySelected: {
    borderColor: 'color-mix(in srgb, var(--color-accent) 44%, var(--color-border))',
    background:  'color-mix(in srgb, var(--color-accent-bg) 42%, transparent)',
    color:       'var(--color-text)',
  },
  trainingWeekDayToday: {
    borderColor: 'color-mix(in srgb, var(--color-accent) 54%, var(--color-border))',
  },
  trainingDayName: {
    color:         'currentColor',
    fontSize:      '11px',
    fontWeight:    700,
    letterSpacing: '0.08em',
  },
  trainingDayType: {
    maxWidth:      '46px',
    color:         'currentColor',
    fontSize:      '9px',
    fontWeight:    620,
    lineHeight:    1.05,
    overflow:      'hidden',
    textOverflow:  'ellipsis',
    whiteSpace:    'nowrap',
  },
  selectedTraining: {
    display:       'flex',
    flexDirection: 'column',
    gap:           '1px',
    padding:       '8px 0 2px',
  },
  workoutHeader: {
    display:       'flex',
    flexDirection: 'column',
    gap:           '3px',
    padding:       '5px 0 8px',
  },
  workoutTitle: {
    margin:      0,
    color:       'var(--color-text)',
    fontFamily: 'var(--font-display)',
    fontSize:   '26px',
    lineHeight: 1.05,
  },
  workoutMeta: {
    margin:     0,
    color:      'var(--color-muted)',
    fontSize:   '12px',
    fontWeight: 540,
  },
  workoutStatus: {
    margin:     '2px 0 0',
    color:      'var(--color-muted)',
    fontSize:   '12px',
    fontWeight: 640,
  },
  workoutStatusDone: {
    color: 'var(--color-success)',
  },
  workoutPreview: {
    display:       'flex',
    flexDirection: 'column',
    gap:           '8px',
    margin:        '8px 0 7px',
    padding:       '8px 0 2px',
    borderTop:     '0.5px solid color-mix(in srgb, var(--color-border) 44%, transparent)',
    borderBottom:  '0.5px solid color-mix(in srgb, var(--color-border) 34%, transparent)',
  },
  detailActions: {
    display:   'flex',
    flexWrap:  'wrap',
    gap:       '5px',
    marginTop: '1px',
  },
  previewGroup: {
    display:       'flex',
    flexDirection: 'column',
    gap:           '2px',
  },
  previewToggle: {
    display:        'flex',
    justifyContent: 'space-between',
    alignItems:     'baseline',
    gap:            '10px',
    width:          '100%',
    padding:        '3px 0',
    background:     'transparent',
    border:         'none',
    color:          'inherit',
    cursor:         'pointer',
  },
  previewTitle: {
    margin:        '0 0 1px',
    color:         'var(--color-muted)',
    fontSize:      '10px',
    fontWeight:    700,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  previewCount: {
    color:      'var(--color-muted)',
    fontSize:   '10px',
    fontWeight: 540,
    whiteSpace: 'nowrap',
  },
  previewRows: {
    display:       'flex',
    flexDirection: 'column',
    gap:           '1px',
    paddingBottom: '4px',
  },
  previewCommonEquipment: {
    margin:     '0 0 2px',
    color:      'var(--color-muted)',
    fontSize:   '10px',
    fontWeight: 520,
  },
  previewRow: {
    display:             'grid',
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    gap:                 '6px',
    alignItems:          'baseline',
    minHeight:           '20px',
    padding:             '1px 0',
  },
  previewName: {
    minWidth:    0,
    color:       'var(--color-text)',
    fontSize:    '12px',
    fontWeight:  560,
    overflow:    'hidden',
    textOverflow:'ellipsis',
    whiteSpace:  'nowrap',
  },
  previewPrescription: {
    color:      'var(--color-accent)',
    fontSize:   '11px',
    fontWeight: 650,
    whiteSpace: 'nowrap',
  },
  previewEquipment: {
    gridColumn: '1 / 3',
    color:      'var(--color-muted)',
    fontSize:   '10px',
    fontWeight: 520,
    lineHeight: 1.25,
  },
  row: {
    display:             'grid',
    gridTemplateColumns: '76px minmax(0, 1fr) auto',
    alignItems:          'center',
    gap:                 '7px',
    minHeight:           '19px',
    padding:             '1px 0',
    borderTop:           'none',
  },
  rowLabel: {
    color:      'var(--color-muted)',
    fontSize:   '11px',
    fontWeight: 560,
  },
  rowValue: {
    minWidth:   0,
    color:      'var(--color-text)',
    fontSize:   '12px',
    fontWeight: 560,
    overflow:   'hidden',
    textOverflow:'ellipsis',
    whiteSpace: 'nowrap',
  },
  rowDetail: {
    color:      'var(--color-muted)',
    fontSize:   '10px',
    fontWeight: 520,
    whiteSpace: 'nowrap',
  },
  rowDetailLong: {
    gridColumn: '2 / 4',
    whiteSpace: 'normal',
    lineHeight: 1.3,
    marginTop:  '-2px',
  },
  meter: {
    gridColumn:   '2 / 4',
    height:       '3px',
    borderRadius: '999px',
    background:   'var(--color-chart-bar)',
    overflow:     'hidden',
  },
  meterFill: {
    display:      'block',
    height:       '100%',
    borderRadius: '999px',
    background:   'var(--color-accent)',
  },
  actions: {
    display:   'flex',
    flexWrap:  'wrap',
    gap:       '5px',
    marginTop: '1px',
  },
  inlineActions: {
    display:   'flex',
    flexWrap:  'wrap',
    gap:       '5px',
    marginTop: '2px',
  },
  action: {
    minHeight:    '22px',
    border:       'none',
    borderRadius: '999px',
    background:   'var(--color-accent)',
    color:        '#fff',
    fontSize:     '10px',
    fontWeight:   650,
    padding:      '3px 8px',
  },
  secondaryAction: {
    border:     'var(--border)',
    background: 'transparent',
    color:      'var(--color-text)',
  },
  checkRow: {
    display:             'grid',
    gridTemplateColumns: '76px minmax(0, 1fr)',
    alignItems:          'center',
    gap:                 '7px',
    padding:             '1px 0',
    borderTop:           'none',
  },
  checkLabel: {
    color:      'var(--color-muted)',
    fontSize:   '11px',
    fontWeight: 560,
  },
  segment: {
    display:             'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap:                 '4px',
  },
  segmentButton: {
    minHeight:    '23px',
    border:       'var(--border)',
    borderRadius: '999px',
    background:   'transparent',
    color:        'var(--color-muted)',
    fontSize:     '10px',
    fontWeight:   620,
    padding:      '3px 4px',
  },
  segmentActive: {
    borderColor: 'var(--color-accent)',
    background:  'var(--color-accent-bg)',
    color:       'var(--color-accent)',
  },
  sheetBackdrop: {
    position:       'fixed',
    inset:          0,
    zIndex:         180,
    display:        'flex',
    alignItems:     'flex-end',
    justifyContent: 'center',
    background:     'rgba(24, 24, 18, 0.22)',
  },
  sheet: {
    width:        '100%',
    maxWidth:     'var(--max-width)',
    maxHeight:    '82dvh',
    overflowY:    'auto',
    background:   'var(--color-bg)',
    borderTop:    'var(--border)',
    padding:      '16px 20px calc(var(--safe-bottom) + 18px)',
    boxShadow:    '0 -14px 38px rgba(24, 24, 18, 0.14)',
  },
  sheetHeader: {
    display:        'flex',
    alignItems:     'center',
    justifyContent: 'space-between',
    gap:            '12px',
    marginBottom:   '10px',
  },
  sheetTitle: {
    margin:      0,
    fontFamily: 'var(--font-display)',
    fontSize:   '18px',
    fontWeight: 500,
  },
  closeButton: {
    border:     'none',
    background: 'transparent',
    color:      'var(--color-muted)',
    fontSize:   '12px',
    fontWeight: 750,
    padding:    '4px 0',
  },
  stepMeta: {
    color:         'var(--color-muted)',
    fontSize:      '10px',
    fontWeight:    750,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    marginBottom:  '10px',
  },
  sheetBody: {
    display:       'flex',
    flexDirection: 'column',
    gap:           '12px',
  },
  fieldStack: {
    display:       'flex',
    flexDirection: 'column',
    gap:           '6px',
  },
  fieldLabel: {
    display:      'block',
    margin:       '0 0 6px',
    color:        'var(--color-muted)',
    fontSize:     '10px',
    fontWeight:   750,
  },
  lineInput: {
    width:        '100%',
    minHeight:    '38px',
    border:       'var(--border)',
    borderRadius: '8px',
    background:   'transparent',
    color:        'var(--color-text)',
    font:         'inherit',
    fontSize:     '14px',
    padding:      '8px 10px',
  },
  textarea: {
    width:        '100%',
    border:       'var(--border)',
    borderRadius: '8px',
    background:   'transparent',
    color:        'var(--color-text)',
    font:         'inherit',
    fontSize:     '14px',
    padding:      '9px 10px',
    resize:       'vertical',
  },
  exerciseList: {
    display:       'flex',
    flexDirection: 'column',
    gap:           '8px',
  },
  exerciseRow: {
    display:       'flex',
    flexDirection: 'column',
    gap:           '6px',
    paddingBottom: '8px',
    borderBottom:  '0.5px solid color-mix(in srgb, var(--color-border) 58%, transparent)',
  },
  exerciseNameInput: {
    minHeight: '36px',
  },
  exerciseGrid: {
    display:             'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap:                 '6px',
  },
  optionGrid: {
    display:             'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap:                 '6px',
  },
  optionButton: {
    minHeight:    '35px',
    border:       'var(--border)',
    borderRadius: '8px',
    background:   'transparent',
    color:        'var(--color-text)',
    fontSize:     '11px',
    fontWeight:   700,
    padding:      '7px 9px',
    textAlign:    'left',
  },
  optionActive: {
    borderColor: 'var(--color-accent)',
    background:  'var(--color-accent-bg)',
    color:       'var(--color-accent)',
  },
  equipmentHint: {
    margin:    '0 0 8px',
    color:     'var(--color-muted)',
    fontSize:  '11px',
    lineHeight: 1.3,
  },
  equipmentGrid: {
    display:    'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap:        '8px',
  },
  equipmentItem: {
    display:        'flex',
    alignItems:     'center',
    gap:            '6px',
    padding:        '8px 10px',
    border:         'var(--border)',
    borderRadius:   'var(--radius-sm)',
    background:     'transparent',
    color:          'var(--color-text)',
    fontSize:       '12px',
    fontWeight:     500,
    textAlign:      'left',
    cursor:         'pointer',
    transition:     'border-color 0.15s, background 0.15s',
  },
  equipmentItemSelected: {
    borderColor: 'var(--color-accent)',
    background:  'var(--color-accent-bg)',
    color:       'var(--color-accent)',
  },
  equipmentCheckbox: {
    display:        'flex',
    alignItems:     'center',
    justifyContent: 'center',
    width:          '16px',
    height:         '16px',
    borderRadius:   '3px',
    border:         '1px solid currentColor',
    fontSize:       '11px',
    fontWeight:     600,
    flexShrink:     0,
  },
  equipmentLabel: {
    flex: 1,
  },
  sheetActions: {
    display:        'flex',
    justifyContent: 'space-between',
    gap:            '8px',
    marginTop:      '16px',
  },
  journalList: {
    display:       'flex',
    flexDirection: 'column',
    gap:           '2px',
  },
  journalRow: {
    display:             'grid',
    gridTemplateColumns: '58px minmax(0, 1fr)',
    gap:                 '4px 10px',
    alignItems:          'baseline',
    minHeight:           '34px',
    padding:             '5px 0',
    borderTop:           '0.5px solid color-mix(in srgb, var(--color-border) 50%, transparent)',
  },
  journalDate: {
    gridRow:    '1 / 3',
    color:      'var(--color-muted)',
    fontSize:   '11px',
    fontWeight: 700,
  },
  journalMeta: {
    color:     'var(--color-muted)',
    fontSize:  '11px',
  },
}
